server:
  port: 8085
  servlet:
    context-path: /booking

# Database configuration for PostgresSQL
spring:
  application:
    name: booking
    version: 1.0
  datasource:
    url: jdbc:postgresql://localhost:5433/tripply
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  base-url: http://localhost:8080
  notification:
    base-url: http://NOTIFICATION
  auth:
    base-url: http://AUTH
  booking:
    base-url: http://BOOKING

swagger-url: http://BOOKING/booking/swagger-ui/index.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost