server:
  port: 8087
  servlet:
    context-path: /booking

# Database configuration for PostgresSQL
spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/Booking_Service
    username: postgres
    password: root
  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update

app:
  base-url: http://localhost:8080
  notification:
    base-url: http://localhost:8087
  auth:
    base-url: http://localhost:8085